# doc https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml

[versions]
selfGradlePlugins = "2.0.0-beta+113"

# Build dependencies
agp = "8.2.0"
kotlin = "1.9.25"
detekt = "1.23.3"
asm = "9.6"

# Android libraries
androidxAnnotation = "1.0.0"
androidxAnnotationJvm = "1.6.0"
installreferrer = "2.2"
playServicesAppset = "16.1.0"
playServicesLocation = "21.0.1"

# External libraries
okhttp = "4.11.0" # check minSDK and proguard before update: https://github.com/square/okhttp/tree/master
commonLogger = "7.0.0"

# Ad revenue adapters
playServicesAds = "23.6.0"
playServicesAdsIdentifier = "18.1.0"
fyberFairbid = "3.59.0"
applovin = "13.1.0"
ironsourceV7 = "8.10.0"
ironsourceV9 = "9.0.0"

# Billing
billingV6 = "7.1.1"
billingV8 = "8.0.0"

# Apphud
apphudV2 = "2.9.2"
apphudV3 = "3.0.0"

# Test dependencies
junit = "4.13.2"
assertj = "3.26.3"
mockitoInline = "5.2.0"
mockitoKotlin = "4.1.0"
robolectric = "4.16"
ktlint = "0.43.2"
equalsverifier = "3.15.2"
jsonassert = "1.5.0"

[plugins]
appMetricaCheckNamespace = { id = "io.appmetrica.gradle.check-namespace", version.ref = "selfGradlePlugins" }
appMetricaCodequality = { id = "io.appmetrica.gradle.codequality", version.ref = "selfGradlePlugins" }
appMetricaGradlePlugin = { id = "io.appmetrica.gradle.gradle-plugin", version.ref = "selfGradlePlugins" }
appMetricaKotlinLibrary = { id = "io.appmetrica.gradle.kotlin-library", version.ref = "selfGradlePlugins" }
appMetricaNoStringDependencies = { id = "io.appmetrica.gradle.no-string-dependencies", version.ref = "selfGradlePlugins" }
appMetricaProto = { id = "io.appmetrica.gradle.proto", version.ref = "selfGradlePlugins" }

[libraries]
# AppMetrica Gradle plugins
appMetricaAarCheck = { module = "io.appmetrica.gradle:aar-check", version.ref = "selfGradlePlugins" }
appMetricaAndroidLibrary = { module = "io.appmetrica.gradle:android-library", version.ref = "selfGradlePlugins" }
appMetricaMavenCentralPublish = { module = "io.appmetrica.gradle:maven-central-publish", version.ref = "selfGradlePlugins" }
appMetricaNoLogs = { module = "io.appmetrica.gradle:no-logs", version.ref = "selfGradlePlugins" }
appMetricaRepositories = { module = "io.appmetrica.gradle:repositories", version.ref = "selfGradlePlugins" }

# AppMetrica dependencies
commonAssertions = { module = "io.appmetrica.analytics:common_assertions" }

# Build dependencies
androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detektGradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }

# Kotlin libraries
kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

# Android libraries
androidxAnnotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidxAnnotationJvm = { module = "androidx.annotation:annotation-jvm", version.ref = "androidxAnnotationJvm" }

installreferrer = { module = "com.android.installreferrer:installreferrer", version.ref = "installreferrer" }
playServicesAppset = { module = "com.google.android.gms:play-services-appset", version.ref = "playServicesAppset" }
playServicesLocation = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }

# External libraries
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpMockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
commonLogger = { module = "io.appmetrica.analytics:analytics-common-logger", version.ref = "commonLogger" }

# Ad revenue adapters
playServicesAds = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
playServicesAdsIdentifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "playServicesAdsIdentifier" }
fyberFairbid = { module = "com.fyber:fairbid-sdk", version.ref = "fyberFairbid" }
applovin = { module = "com.applovin:applovin-sdk", version.ref = "applovin" }
ironsourceV7 = { module = "com.unity3d.ads-mediation:mediation-sdk", version.ref = "ironsourceV7" }
ironsourceV9 = { module = "com.unity3d.ads-mediation:mediation-sdk", version.ref = "ironsourceV9" }

# Billing
billingV6 = { module = "com.android.billingclient:billing", version.ref = "billingV6" }
billingV8 = { module = "com.android.billingclient:billing", version.ref = "billingV8" }

# Apphud
apphudV2 = { module = "com.apphud:ApphudSDK-Android", version.ref = "apphudV2" }
apphudV3 = { module = "com.apphud:ApphudSDK-Android", version.ref = "apphudV3" }

# Test dependencies
junit = { module = "junit:junit", version.ref = "junit" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockitoInline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
ktlintCore = { module = "com.pinterest.ktlint:ktlint-core", version.ref = "ktlint" }
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsverifier" }
jsonassert = { module = "org.skyscreamer:jsonassert", version.ref = "jsonassert" }
